name: test-environment
channels:
- conda-forge
dependencies:
- python==3.10.4
- pip==22.1.2
- numpy==1.21.0
- scipy==1.8.1
- matplotlib==3.5.2
- imagemagick==7.1.0_36
- jupyter==3.1.2
- pytest==7.1.2
- nbmake==1.3.0
- jupytext==1.13.8
