name: CI build

on:
  [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  pytests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - qutip-branch: 'master'
            path_md: 'tutorials-v4/*.md'
            path_ipynb: 'tutorials-v4/*.ipynb'
          - qutip-branch: 'dev.major'
            path_md: 'tutorials-v5/*.md'
            path_ipynb: 'tutorials-v5/*.ipynb'
    steps:
    - uses: actions/checkout@v3
    - name: Conda cache
      uses: actions/cache@v3
      env:
        # Increase this number to reset cache
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('test_environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        environment-file: test_environment.yml
        channel-priority: strict
        use-only-tar-bz2: true
        use-mamba: true

    - name: Install QuTiP and QuTiP-QIP
      run: |
        pip install --upgrade pip
        git clone -b ${{ matrix.qutip-branch }} https://github.com/qutip/qutip.git
        cd qutip
        pip install -r requirements.txt
        python setup.py develop
        cd ..
        git clone -b master https://github.com/qutip/qutip-qip.git
        cd qutip-qip
        pip install -e .

    - name: Convert Notebooks and create index
      run: | 
        rm -rf notebooks
        mkdir notebooks
        jupytext --to notebook ${{ matrix.path_md }}
        mv ${{ matrix.path_ipynb}} notebooks
        sudo apt-get install tree
        cd notebooks
        tree -H '.' -L 1 --noreport --charset utf-8 -T "QuTiP Tutorial index" -P "*.ipynb" -o index.html

    - name: Run tests
      run: |
        jupyter kernel &
        pytest --nbmake notebooks/*.ipynb --overwrite --nbmake-timeout=500

    - name: Create Notebook Artifact
      if: ${{ matrix.qutip-branch == 'master' }}
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebooks
        path: notebooks/*
  publish:
    needs: pytests
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'qutip/qutip-tutorials' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: executed-notebooks
          path: notebooks

      - name: Publish Notebooks
        run: | 
          python -m pip install ghp-import
          ghp-import -m "Automatic push by ghp-import" -f -n -p -o -r origin -b gh-pages notebooks

