name: CI build

on:
  [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  pytests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        environment-file: test_environment.yml
        auto-activate-base: false
        auto-update-conda: true

    - name: Install QuTiP and QuTiP-QIP
      run: |
        sudo apt-get install git
        pip install --upgrade pip
        git clone https://github.com/qutip/qutip.git
        cd qutip
        pip install -r requirements.txt
        python setup.py develop
        cd ..
        git clone https://github.com/qutip/qutip-qip.git
        cd qutip-qip
        pip install -e .

    - name: Convert Notebooks
      run: | 
        rm -rf notebooks
        mkdir notebooks
        jupytext --to notebook tutorials/*.md
        mv tutorials/*.ipynb notebooks

    - name: Run tests
      run: |
        jupyter kernel &
        pytest --nbmake notebooks/*.ipynb --overwrite --nbmake-timeout=500

    - name: Create Notebook Artifact
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebooks
        path: notebooks/*.ipynb

  publish:
    needs: pytests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: executed-notebooks
          path: notebooks

      - name: Install ghp-import
        run: | 
          python -m pip install ghp-import

      - name: Publish Notebooks
        run: | 
          ghp-import -m "Automatic push by ghp-import" -f -o -r origin -b gh-pages notebooks

