name: Publish

on:
  [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: publish

      - uses: actions/download-artifact@master
        with:
          name: executed-notebooks
          path: tutorials/notebooks

      - name: Set git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit Notebooks to Publish branch
        run: |
          git add tutorials/notebooks/*.ipynb
          git commit -m "publish notebooks"
          git push origin publish